version: '3'


services:

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/cross-platform-productivity-backend
    ports:
      - "5000:5000"
    depends_on:
      - redis
    links:
      - redis
      

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/cross-platform-productivity-frontend
    ports:
      - "8000:8000"
    depends_on:
      - backend
      - redis

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"